name = "MathJSON"
uuid = "77215b4b-6f01-425c-beac-950ae6536d4d"
version = "0.2.1"
authors = ["SÃ©bastien Celles <s.celles@gmail.com>"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[weakdeps]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
MathJSONSymbolicsExt = ["Symbolics", "SymbolicUtils"]

[compat]
Aqua = "0.8"
JSON3 = "1.14"
JSONSchema = "1"
SymbolicUtils = "3"
Symbolics = "6"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JSONSchema", "Test", "Symbolics", "SymbolicUtils"]
